### ISSUE TITLE
thanks for your project ！！！

### ISSUE THREAD

**Issue by lxb-foxer** [Ricolxwz/Learning-Math#1]

**Comment by lxb-foxer** [comment]
求概率论

![01EA2F9C](https://github.com/Ricolxwz/Kaoyanshuxue/assets/75427939/73d3d398-4a36-4d24-86a6-9bbecb39329c)

**Comment by ricolxwz** [comment]
木有概率论哈哈哈我是数二没有写

**Comment by lxb-foxer** [comment]
好的，谢谢您愿意回复我，我会按照您的方法去试一下的，我考数一，一来想在您的高数和线代里面添加一些我自己的笔记和公式，二来想看看能不能完成下概率论，谢谢您能教我，希望没有打扰到您！，谢谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ricolxwz/Kaoyanshuxue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 中午1:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ricolxwz/Kaoyanshuxue] thanks for your project ！！！ (Issue #1)





 
木有概率论哈哈哈我是数二没有写

**Comment by ricolxwz** [comment]
完全没问题哒, 概率论近期暂时没有时间哦, 在读硕士~
